version: '3'
services:
  stock_web_scrapper:
    build: .
    container_name: stock_web_scrapper
    restart: unless-stopped
    volumes:
      - ./stockwebscrapper:/usr/src/app
    command: "python stock_web_scrapper.py"
    tty: true