version: '3'
services:
  stock_web_scrapper:
    image: localhost:5000/docker_stockwebscrapper_v2
    restart: unless-stopped
    volumes:
      - ./stockwebscrapper:/usr/src/app
    command: "python stock_web_scrapper.py"
    tty: true
